spring.application.name=spring-boot-async-aggregator
# =========================
# PostgreSQL Configuration
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Redis Configuration
# =========================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# =========================
# Cache Configuration
# =========================
spring.cache.type=redis

# =========================
# Logging (Optional)
# =========================
logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.data.redis=INFO